# using only for get_perspective_hcas.py

dataset_params:
  apply_color_aug: true #whether to apply photometric distortions
  image_height: 480 
  image_width: 640
  resize_aspect: false #whether to resize the input image with aspect ratio maintained
  augmentation_params:
    patch_ratio: 0.85 
    #All the below params are ranges for distortion. (0, Mentioned_value). 
    #Refer 'get_perspective_mat' function in utils/preprocess_utils.py for more info
    perspective_x: 0.0008 # range for perspective-x component
    perspective_y: 0.0008 #range of perspective-y component
    shear_ratio: 0.04 #shear ratio range
    shear_angle: 10 #shear direction range
    rotation_angle: 180 #rotation angle range #! was 360 but it should be 180. look at function!
    scale: 0.2 #uniform scaling range
    translation: 0.2 #translation component range